// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteOrder is an autogenerated mock type for the DeleteOrder type
type DeleteOrder struct {
	mock.Mock
}

// DeleteOrder provides a mock function with given fields: name
func (_m *DeleteOrder) DeleteOrder(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeleteOrder creates a new instance of DeleteOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteOrder(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteOrder {
	mock := &DeleteOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
