// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	sqlite "github.com/Weit145/REST_API_golang/internal/storage/sqlite"
	mock "github.com/stretchr/testify/mock"
)

// CreateOrder is an autogenerated mock type for the CreateOrder type
type CreateOrder struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: order
func (_m *CreateOrder) CreateOrder(order sqlite.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(sqlite.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCreateOrder creates a new instance of CreateOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateOrder(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateOrder {
	mock := &CreateOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
