// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	sqlite "github.com/Weit145/REST_API_golang/internal/storage/sqlite"
)

// ReadOrder is an autogenerated mock type for the ReadOrder type
type ReadOrder struct {
	mock.Mock
}

// ReadOrder provides a mock function with given fields: name
func (_m *ReadOrder) ReadOrder(name string) (sqlite.Order, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadOrder")
	}

	var r0 sqlite.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (sqlite.Order, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) sqlite.Order); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(sqlite.Order)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReadOrder creates a new instance of ReadOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadOrder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadOrder {
	mock := &ReadOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
