// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	sqlite "github.com/Weit145/REST_API_golang/internal/storage/sqlite"
	mock "github.com/stretchr/testify/mock"
)

// UpdateOrder is an autogenerated mock type for the UpdateOrder type
type UpdateOrder struct {
	mock.Mock
}

// UpdateOrder provides a mock function with given fields: order
func (_m *UpdateOrder) UpdateOrder(order sqlite.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(sqlite.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUpdateOrder creates a new instance of UpdateOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateOrder(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateOrder {
	mock := &UpdateOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
